import { CardData } from "../../pages/Tarifs/TypesInterfaces";

export const cardData: CardData[] = [
  {
    title: "Basique",
    description: "Les outils dont vous avez besoin pour une protection de base",
    price: "$55.99/An",
    monthlyPrice: "$4.58 par mois",
    features: [
      { text: "Blocage des jeux et applications", imgSrc: "/assets/images/icons8-compte-vérifié-96.png" },
      { text: "Limites de temps quotidiennes", imgSrc: "/assets/images/icons8-compte-vérifié-96.png" },
      { text: "Filtrage web", imgSrc: "/assets/images/icons8-compte-vérifié-96.png" },
      { text: "Suivi de la localisation", imgSrc: "/assets/images/icons8-compte-vérifié-96.png" },
      { text: "Pause de l'accès internet", imgSrc: "/assets/images/icons8-compte-vérifié-96.png" },
    ],
    imgSrc: "/assets/images/icons8-cadenas-100.png",
    color: "#F0E5E5",
    textColor: "#000",
  },
  {
    title: "Premium",
    description: "Des outils avancés pour une protection complète",
    price: "$99.99/An",
    monthlyPrice: "$8.33 par mois",
    features: [
      { text: "Blocage des jeux et applications", imgSrc:"/assets/images/icons8-compte-vérifié-96.png" },
      { text: "Limites de temps quotidiennes", imgSrc: "/assets/images/icons8-compte-vérifié-96.png" },
      { text: "Flitrage web", imgSrc: "/assets/images/icons8-compte-vérifié-96.png" },
      { text: "Suivi de la localisation", imgSrc:"/assets/images/icons8-compte-vérifié-96.png" },
      { text: "Pause de l'acces internet", imgSrc: "/assets/images/icons8-compte-vérifié-96.png" },
      { text: "Alertes personnalisee", imgSrc: "/assets/images/icons8-compte-vérifié-96.png" },
      { text: "Surveillance des appels et messages", imgSrc: "/assets/images/icons8-compte-vérifié-96.png" },
      { text: "Appareils illimites", imgSrc: "/assets/images/icons8-compte-vérifié-96.png" },
      { text: "Live view (voir en directe ce que fait votre enfant (sur son telephone depuis votre telephone ) ", imgSrc: "/assets/images/icons8-compte-vérifié-96 (1).png" },
    ],
    imgSrc: "/assets/images/icons8-garantie-60.png",
    color: "#F87501",
    textColor: "#fff",
  },
  {
    title: "Complete",
    description: "Des outils avancés pour une protection complète",
    price: "$99.99/An",
    monthlyPrice: "$8.33 par mois",
    features: [
      { text: "Blocage des jeux et applications", imgSrc: "/assets/images/icons8-compte-vérifié-96.png" },
      { text: "Limites de temps quotidiennes", imgSrc: "/assets/images/icons8-compte-vérifié-96.png" },
      { text: "Flitrage web", imgSrc: "/assets/images/icons8-compte-vérifié-96.png" },
      { text: "Suivi de la localisation", imgSrc: "/assets/images/icons8-compte-vérifié-96.png" },
      { text: "Pause de l'acces internet", imgSrc: "/assets/images/icons8-compte-vérifié-96.png" },
      { text: "Alertes personnalisee", imgSrc: "/assets/images/icons8-compte-vérifié-96.png" },
      { text: "Surveillance des appels et messages", imgSrc: "/assets/images/icons8-compte-vérifié-96.png" },
      { text: "Appareils illimites", imgSrc: "/assets/images/icons8-compte-vérifié-96.png" },
    ],
    imgSrc: "/assets/images/icons8-protection-du-trou-de-serrure-96.png",
    color: "#4652AC",
    textColor: "#fff",
  },
];
